// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/schema/registry/v1/register_schema_success.proto

package registryv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RegisterSchemaSuccess is the success message if a register schema is successful or the schema already exists.
type RegisterSchemaSuccess struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSchemaSuccess) Reset()         { *m = RegisterSchemaSuccess{} }
func (m *RegisterSchemaSuccess) String() string { return proto.CompactTextString(m) }
func (*RegisterSchemaSuccess) ProtoMessage()    {}
func (*RegisterSchemaSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_08519a05b3e4bed1, []int{0}
}

func (m *RegisterSchemaSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSchemaSuccess.Unmarshal(m, b)
}
func (m *RegisterSchemaSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSchemaSuccess.Marshal(b, m, deterministic)
}
func (m *RegisterSchemaSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSchemaSuccess.Merge(m, src)
}
func (m *RegisterSchemaSuccess) XXX_Size() int {
	return xxx_messageInfo_RegisterSchemaSuccess.Size(m)
}
func (m *RegisterSchemaSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSchemaSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSchemaSuccess proto.InternalMessageInfo

func (m *RegisterSchemaSuccess) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterSchemaSuccess)(nil), "proto.schema.registry.v1.RegisterSchemaSuccess")
}

func init() {
	proto.RegisterFile("proto/schema/registry/v1/register_schema_success.proto", fileDescriptor_08519a05b3e4bed1)
}

var fileDescriptor_08519a05b3e4bed1 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0x2f, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x29,
	0xaa, 0xd4, 0x2f, 0x33, 0x84, 0xb2, 0x53, 0x8b, 0xe2, 0x21, 0x72, 0xf1, 0xc5, 0xa5, 0xc9, 0xc9,
	0xa9, 0xc5, 0xc5, 0x7a, 0x60, 0x0d, 0x42, 0x12, 0x60, 0x4a, 0x0f, 0x22, 0xa7, 0x07, 0xd3, 0xa7,
	0x57, 0x66, 0xa8, 0xa4, 0xce, 0x25, 0x1a, 0x04, 0xd5, 0x1a, 0x0c, 0x96, 0x0d, 0x86, 0x68, 0x14,
	0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x71,
	0x4a, 0xe6, 0x92, 0x49, 0xce, 0xcf, 0xd5, 0xc3, 0x65, 0x90, 0x93, 0x14, 0x56, 0x63, 0x02, 0x40,
	0xca, 0x03, 0x18, 0xa3, 0xb8, 0x60, 0x4a, 0xcb, 0x0c, 0x57, 0x31, 0x49, 0x80, 0x45, 0xf5, 0x20,
	0x0a, 0xf5, 0x82, 0x60, 0x86, 0x84, 0x19, 0x26, 0xb1, 0x81, 0x8d, 0x37, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xec, 0xc0, 0x6d, 0xc1, 0xe8, 0x00, 0x00, 0x00,
}
