// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/schema/registry/v1/register_schema_error.proto

package registryv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RegisterSchemaError are the errors returned if a register schema fails.
type RegisterSchemaError struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSchemaError) Reset()         { *m = RegisterSchemaError{} }
func (m *RegisterSchemaError) String() string { return proto.CompactTextString(m) }
func (*RegisterSchemaError) ProtoMessage()    {}
func (*RegisterSchemaError) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fcf13649baa4e, []int{0}
}

func (m *RegisterSchemaError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSchemaError.Unmarshal(m, b)
}
func (m *RegisterSchemaError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSchemaError.Marshal(b, m, deterministic)
}
func (m *RegisterSchemaError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSchemaError.Merge(m, src)
}
func (m *RegisterSchemaError) XXX_Size() int {
	return xxx_messageInfo_RegisterSchemaError.Size(m)
}
func (m *RegisterSchemaError) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSchemaError.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSchemaError proto.InternalMessageInfo

func (m *RegisterSchemaError) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterSchemaError)(nil), "proto.schema.registry.v1.RegisterSchemaError")
}

func init() {
	proto.RegisterFile("proto/schema/registry/v1/register_schema_error.proto", fileDescriptor_e54fcf13649baa4e)
}

var fileDescriptor_e54fcf13649baa4e = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0x2f, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x29,
	0xaa, 0xd4, 0x2f, 0x33, 0x84, 0xb2, 0x53, 0x8b, 0xe2, 0x21, 0x72, 0xf1, 0xa9, 0x45, 0x45, 0xf9,
	0x45, 0x7a, 0x60, 0xe5, 0x42, 0x12, 0x60, 0x4a, 0x0f, 0x22, 0xa3, 0x07, 0xd3, 0xa5, 0x57, 0x66,
	0xa8, 0xa4, 0xcb, 0x25, 0x1c, 0x04, 0xd5, 0x18, 0x0c, 0x96, 0x75, 0x05, 0x69, 0x13, 0x12, 0xe3,
	0x62, 0x03, 0xeb, 0x2f, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf2, 0x9c, 0x12, 0xb9,
	0x64, 0x92, 0xf3, 0x73, 0xf5, 0x70, 0x19, 0xe7, 0x24, 0x81, 0xc5, 0xb0, 0x00, 0x90, 0xe2, 0x00,
	0xc6, 0x28, 0x2e, 0x98, 0xc2, 0x32, 0xc3, 0x55, 0x4c, 0x12, 0x60, 0x51, 0x3d, 0x88, 0x32, 0xbd,
	0x20, 0x98, 0x11, 0x61, 0x86, 0x49, 0x6c, 0x60, 0xc3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xc4, 0xb0, 0x20, 0x00, 0xea, 0x00, 0x00, 0x00,
}
