// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/enums.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enum1 int32

const (
	Enum1_ZERO  Enum1 = 0
	Enum1_ONE   Enum1 = 1
	Enum1_TWO   Enum1 = 2
	Enum1_THREE Enum1 = 3
	Enum1_FOUR  Enum1 = 4
)

var Enum1_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
	2: "TWO",
	3: "THREE",
	4: "FOUR",
}

var Enum1_value = map[string]int32{
	"ZERO":  0,
	"ONE":   1,
	"TWO":   2,
	"THREE": 3,
	"FOUR":  4,
}

func (x Enum1) String() string {
	return proto.EnumName(Enum1_name, int32(x))
}

func (Enum1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_80c7ec401998e878, []int{0}
}

type EnumMessage_Enum2 int32

const (
	EnumMessage_STUFF EnumMessage_Enum2 = 0
	EnumMessage_PIE   EnumMessage_Enum2 = 1
)

var EnumMessage_Enum2_name = map[int32]string{
	0: "STUFF",
	1: "PIE",
}

var EnumMessage_Enum2_value = map[string]int32{
	"STUFF": 0,
	"PIE":   1,
}

func (x EnumMessage_Enum2) String() string {
	return proto.EnumName(EnumMessage_Enum2_name, int32(x))
}

func (EnumMessage_Enum2) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_80c7ec401998e878, []int{0, 0}
}

type EnumMessage struct {
	Enum1Message         Enum1             `protobuf:"varint,1,opt,name=enum1_message,json=enum1Message,proto3,enum=v1.Enum1" json:"enum1_message,omitempty"`
	Enum2Message         EnumMessage_Enum2 `protobuf:"varint,2,opt,name=enum2_message,json=enum2Message,proto3,enum=v1.EnumMessage_Enum2" json:"enum2_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_80c7ec401998e878, []int{0}
}

func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (m *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(m, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetEnum1Message() Enum1 {
	if m != nil {
		return m.Enum1Message
	}
	return Enum1_ZERO
}

func (m *EnumMessage) GetEnum2Message() EnumMessage_Enum2 {
	if m != nil {
		return m.Enum2Message
	}
	return EnumMessage_STUFF
}

func init() {
	proto.RegisterEnum("v1.Enum1", Enum1_name, Enum1_value)
	proto.RegisterEnum("v1.EnumMessage_Enum2", EnumMessage_Enum2_name, EnumMessage_Enum2_value)
	proto.RegisterType((*EnumMessage)(nil), "v1.EnumMessage")
}

func init() { proto.RegisterFile("v1/enums.proto", fileDescriptor_80c7ec401998e878) }

var fileDescriptor_80c7ec401998e878 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x33, 0xd4, 0x4f,
	0xcd, 0x2b, 0xcd, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x9a,
	0xc6, 0xc8, 0xc5, 0xed, 0x9a, 0x57, 0x9a, 0xeb, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0xa4,
	0xc7, 0xc5, 0x0b, 0x52, 0x62, 0x18, 0x9f, 0x0b, 0x11, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33,
	0xe2, 0xd4, 0x2b, 0x33, 0xd4, 0x03, 0xa9, 0x33, 0x0c, 0xe2, 0x01, 0xcb, 0xc3, 0xd4, 0x5b, 0x41,
	0xd4, 0x1b, 0xc1, 0xd5, 0x33, 0x81, 0xd5, 0x8b, 0xc2, 0xd4, 0x43, 0xd5, 0x81, 0xd9, 0x46, 0x10,
	0xbd, 0x46, 0x50, 0x31, 0x25, 0x69, 0x2e, 0x56, 0xb0, 0xb0, 0x10, 0x27, 0x17, 0x6b, 0x70, 0x48,
	0xa8, 0x9b, 0x9b, 0x00, 0x83, 0x10, 0x3b, 0x17, 0x73, 0x80, 0xa7, 0xab, 0x00, 0xa3, 0x96, 0x05,
	0x44, 0xd2, 0x50, 0x88, 0x83, 0x8b, 0x25, 0xca, 0x35, 0xc8, 0x1f, 0x22, 0xe7, 0xef, 0xe7, 0x2a,
	0xc0, 0x08, 0x62, 0x84, 0x84, 0xfb, 0x0b, 0x30, 0x81, 0x34, 0x86, 0x78, 0x04, 0xb9, 0xba, 0x0a,
	0x30, 0x83, 0x94, 0xb9, 0xf9, 0x87, 0x06, 0x09, 0xb0, 0x24, 0xb1, 0x81, 0x7d, 0x67, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x41, 0x3a, 0x3f, 0xef, 0x00, 0x00, 0x00,
}
