// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/testObjects.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestObjects struct {
	Object               *TestObject       `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Object_2             *TestObject2      `protobuf:"bytes,2,opt,name=object_2,json=object2,proto3" json:"object_2,omitempty"`
	Object_3             *TestObject3      `protobuf:"bytes,3,opt,name=object_3,json=object3,proto3" json:"object_3,omitempty"`
	EnumMessage          *EnumMessage      `protobuf:"bytes,4,opt,name=enum_message,json=enumMessage,proto3" json:"enum_message,omitempty"`
	EnumInsideMessage    EnumMessage_Enum2 `protobuf:"varint,5,opt,name=enum_inside_message,json=enumInsideMessage,proto3,enum=v1.EnumMessage_Enum2" json:"enum_inside_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TestObjects) Reset()         { *m = TestObjects{} }
func (m *TestObjects) String() string { return proto.CompactTextString(m) }
func (*TestObjects) ProtoMessage()    {}
func (*TestObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_216169bec99a1bfa, []int{0}
}

func (m *TestObjects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestObjects.Unmarshal(m, b)
}
func (m *TestObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestObjects.Marshal(b, m, deterministic)
}
func (m *TestObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestObjects.Merge(m, src)
}
func (m *TestObjects) XXX_Size() int {
	return xxx_messageInfo_TestObjects.Size(m)
}
func (m *TestObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_TestObjects.DiscardUnknown(m)
}

var xxx_messageInfo_TestObjects proto.InternalMessageInfo

func (m *TestObjects) GetObject() *TestObject {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *TestObjects) GetObject_2() *TestObject2 {
	if m != nil {
		return m.Object_2
	}
	return nil
}

func (m *TestObjects) GetObject_3() *TestObject3 {
	if m != nil {
		return m.Object_3
	}
	return nil
}

func (m *TestObjects) GetEnumMessage() *EnumMessage {
	if m != nil {
		return m.EnumMessage
	}
	return nil
}

func (m *TestObjects) GetEnumInsideMessage() EnumMessage_Enum2 {
	if m != nil {
		return m.EnumInsideMessage
	}
	return EnumMessage_STUFF
}

func init() {
	proto.RegisterType((*TestObjects)(nil), "v1.TestObjects")
}

func init() { proto.RegisterFile("v1/testObjects.proto", fileDescriptor_216169bec99a1bfa) }

var fileDescriptor_216169bec99a1bfa = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x33, 0xd4, 0x2f,
	0x49, 0x2d, 0x2e, 0xf1, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x33, 0x94, 0x12, 0x46, 0x91, 0x81, 0x48, 0x48, 0xa1, 0x2a, 0x37, 0xc2, 0x2a,
	0x6a, 0x0c, 0x15, 0xe5, 0x2b, 0x33, 0xd4, 0x4f, 0xcd, 0x2b, 0xcd, 0x85, 0x1a, 0xaa, 0xd4, 0xc1,
	0xc4, 0xc5, 0x1d, 0x82, 0xb0, 0x4a, 0x48, 0x8d, 0x8b, 0x2d, 0x1f, 0xcc, 0x94, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x36, 0xe2, 0xd3, 0x2b, 0x33, 0xd4, 0x43, 0x28, 0x08, 0x82, 0xca, 0x0a, 0x69, 0x71,
	0x71, 0x40, 0x58, 0xf1, 0x46, 0x12, 0x4c, 0x60, 0x95, 0xfc, 0xa8, 0x2a, 0x8d, 0x82, 0xd8, 0x21,
	0x0a, 0x8c, 0x90, 0xd4, 0x1a, 0x4b, 0x30, 0x63, 0x53, 0x6b, 0x0c, 0x53, 0x6b, 0x2c, 0x64, 0xc4,
	0xc5, 0x03, 0x72, 0x5e, 0x7c, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x04, 0x0b, 0x42, 0xbd,
	0x6b, 0x5e, 0x69, 0xae, 0x2f, 0x44, 0x38, 0x88, 0x3b, 0x15, 0xc1, 0x11, 0x72, 0xe5, 0x12, 0x06,
	0xeb, 0xc9, 0xcc, 0x2b, 0xce, 0x4c, 0x49, 0x85, 0x6b, 0x65, 0x55, 0x60, 0xd4, 0xe0, 0x33, 0x12,
	0x45, 0xd3, 0x0a, 0x66, 0x1b, 0x05, 0x09, 0x82, 0x74, 0x78, 0x82, 0x35, 0x40, 0x25, 0x9c, 0x58,
	0xa2, 0x98, 0xca, 0x0c, 0x93, 0xd8, 0xc0, 0xe1, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x01,
	0xd9, 0x82, 0x26, 0x84, 0x01, 0x00, 0x00,
}
